conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.Inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.NewConversationView, name='new')
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view

from . import forms
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.SignupView, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', auth_view.LoginView.as_view(template_name='login.html', authentication_form=forms.AuthenticationForm), name='login')
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    # path('<str:user_name>/', views.index, name='dashboard'),
    path('dashboard/', views.index, name='dashboard'),
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.NewItemView, name='new'),
    path('<int:pk>/delete/', views.DeletItemsView, name='delete'),
    path('<int:pk>/edit/', views.EditItemView, name='edit')
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your emal',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


class LoginForm(AuthenticationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout

from item.models import Item, Category

from .forms import SignupForm


def index(request):
    items = Item.objects.filter(is_sold=False) #[0:6] boshlang'ich 6 ta element bilan cheklaydi ``SELECT * FROM Item WHERE is_sold = False LIMIT=6;``
    categories = Category.objects.all()

    template_name = 'index.html'
    context = {
        "items": items,
        "categories": categories
    }
    return render(request, template_name, context)


def contact(request):
    template_name = 'contact.html'
    context = None
    return render(request, template_name, context)


def SignupView(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignupForm()

    template_name = 'signup.html'
    context = {
        'form': form
    }
    return render(request, template_name, context)

def logout_view(request):
    logout(request)
    return redirect('/')  # Redirect to the login page

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://cdn.tailwindcss.com"></script>

    <title> {% block title %}{% endblock %}/Puddle</title>

</head>
<body>
<nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200 ">
    <a href="/" class="text-xl font-semibold">Puddle</a>
    <div class="space-x-6">
    <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>

    {% if not user.is_authenticated %}
        <a href="{% url 'core:signup' %}" class="px-6 py-2 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
        <a href="{% url 'core:login' %}" class="px-6 py-2 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Login</a>
    {% elif user.is_authenticated %}
        <a href="{% url 'item:new' %}" class="px-6 py-2 text-lg font-semibold bg-green-500 text-white rounded-xl hover:bg-green-700">Add New Item</a>
        <a href="{% url 'conversation:inbox' %}" class="px-6 py-2 text-lg font-semibold bg-green-500 text-white rounded-xl hover:bg-green-700">Inbox</a>
        <a href="{% url 'dashboard:dashboard' %}" class="px-6 py-2 text-lg font-semibold bg-green-500 text-white rounded-xl hover:bg-green-700">Dashboard</a>
        <a href="{% url 'core:logout' %}" class="px-6 py-2 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log out</a>
    {% endif %}
</div>


</nav>
    <div class="px-6 py-6">
        {% block content %}

        {% endblock %}
    </div>
<footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>

                <p class="text-lg text-gray-500">Lorem ipsum bla bla bla. Lorem ipsum bla bla bla. Lorem ipsum bla bla bla.</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>
                </ul>
            </div>
        </footer>
</body>
</html>

core/templates/contact.html
{% extends 'base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
<h1>This is contact page</h1>
{% endblock %}

core/templates/index.html
{% extends 'base.html' %}
{% block title %}Index{% endblock %}
{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Newest Items</h2>

    <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
    {% for item in items %}
        <div class="bg-white shadow-lg rounded-xl overflow-hidden p-4 hover:shadow-2xl hover:scale-105 transition duration-300 ease-in-out">
            <a href="{% url 'item:detail' item.id %}">
                <div>
                    <img src="{{ item.image.url }}" class="w-full h-56 object-cover rounded-xl">
                </div>
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{item.name}}</h2>
                    <p class="text-gray-400">Price: {{item.price}}</p>
                </div>
            </a>
        </div>
    {% endfor %}
</div>
</div>
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Categories</h2>

    <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
        {% for category in categories %}
            <div class="bg-white shadow-lg rounded-xl overflow-hidden p-4 hover:shadow-2xl hover:scale-105 transition duration-300 ease-in-out">
            <a href="#">
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{category.name}}</h2>
                    <p class="text-gray-400">{{category.items.count}} items</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

core/templates/login.html
{% extends 'base.html' %}
{% block title %}SignUp{% endblock%}

{% block content %}
    <div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Login</h1>
        <form method="post" action=".">
            {% csrf_token %}
            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{form.username}}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{form.password}}
            </div>
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    {{ form.non_field_errors}}
                </div>
            {% endif %}
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
        </form>
    </div>
{% endblock %}

core/templates/signup.html
{% extends 'base.html' %}
{% block title %}SignUp{% endblock%}

{% block content %}
    <div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Sign Up</h1>
        <form method="post" action=".">
            {% csrf_token %}

            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{form.username}}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Email</label><br>
                {{form.email}}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{form.password1}}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Confirm password</label><br>
                {{form.password2}}
            </div>
            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    {{ form.non_field_errors}}
                </div>
            {% endif %}
            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
        </form>
    </div>
{% endblock %}