conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.Inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.NewConversationView, name='new')
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.NewItemView, name='new'),
    path('<int:pk>/delete/', views.DeletItemsView, name='delete'),
    path('<int:pk>/edit/', views.EditItemView, name='edit')
]

item/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
import uuid


# class MyUser(AbstractUser):   #AbstaractUser ishlatilishi uchun ni djanog settings da AUTH_USER_MODEL = 'Core.MyUser' belgilash kerak
#     id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name', )  #django admin panelda ordering (sanashni 1,2,3,4,5) faqat nomi bilan korsatadi
        verbose_name_plural = "Categories" #django admin panelda main name shunday nomlarnadi

    def __str__(self):
        return self.name  #django admin panelda nomlari bilan korishga yoradam beradi


class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

item/forms.py
from django import forms
from .models import Item


INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'
class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = {'category', 'name', 'description', 'price', 'image',} #fields da ko'rsatilgan o'rni bo'yicha Frontendda korinadi

        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.NumberInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = {'name', 'description', 'price', 'image', 'is_sold' } #fields da ko'rsatilgan o'rni bo'yicha Frontendda korinadi

        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.NumberInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

item/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from .forms import NewItemForm, EditItemForm
from .models import Item, Category


def items(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)

    if category_id:
        items = items.filter(category_id=category_id)

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))

    template_name = 'items.html'
    context = {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': category_id
    }
    return render(request, template_name, context)

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)

    template_name = 'detail.html'
    context = {
        'item': item,
        'related_items': related_items
    }
    return render(request, template_name, context)

@login_required
def NewItemView(request):
    if request.method == 'POST':                        #so'rov turi tekshirladi
        form = NewItemForm(request.POST, request.FILES) #so'rov turi to'g'ri kelgandan keyin , Formaga so'rov keladi
        if form.is_valid():                             #agar malumot bo'lsa
            item = form.save(commit=False)              #commit = False bu yerda jo'natilgan malumotlarni darhol malumotlar bazasiga saqlmasligni oldini oladi
            item.created_by = request.user              #malumotni kim jo'natilgan malumot egasi aniqlanib uni malumotga qoshib qoyiladi
            item.save()                                 #malumot saqlanadi
            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()

    template_name = 'form.html'
    context = {
        'form': form,
        'title': 'New Item',
    }
    return render(request, template_name, context)


@login_required
def DeletItemsView(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()
    return redirect('dashboard:dashboard')


@login_required
def EditItemView(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            item.save()
            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)

    template_name = 'form.html'
    context = {
        'form': form,
        'title': 'Edit Item',
    }
    return render(request, template_name, context)

item/templates/detail.html
{% extends 'base.html' %}

{% block title%}{{ item.name }}{% endblock %}

{% block content %}
    <div class="grid grid-cols-5 gap-6">
        <div class="bg-white shadow-lg rounded-xl overflow-hidden p-2 hover:shadow-2xl hover:scale-105 transition duration-300 ease-in-out">
            <img src="{{item.image.url}}" class="rounded-xl">
        </div>
        <div class="col-span-3 p-8 bg-gray-100 rounded-xl">
            <h1 class="mb-6 text-3xl">{{item.name}}</h1>
            <p class="text-gray-500">Price: <strong>{{item.price}}</strong></p>
            <p class="text-gray-500">Seller: <strong>{{item.created_by.username}}</strong></p>
            {%if item.description %}
                <p class="text-gray-700 ">
                    <strong class="text-gray-500">Description</strong>
                    {{item.description}}
                </p>
            {%endif%}

            {% if request.user == item.created_by %}
            <div class="mt-6 p-6 bg-white rounded-xl">
                <p>This is your item!</p>
                <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
                <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-green-500 text-teal rounded-xl">Edit</a>
            </div>
            {% else %}
            <a href="{% url 'conversation:new' item.id%}" class="inline-block mt-6 px-6 py-6 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-400">
                Contact seller
            </a>
            {%endif%}
        </div>
    </div>
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Related Items</h2>
    <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
    {% for item in related_items %}
        <div class="bg-white shadow-lg rounded-xl overflow-hidden p-4 hover:shadow-2xl hover:scale-105 transition duration-300 ease-in-out">
            <a href="{% url 'item:detail' item.id %}">
                <div>
                    <img src="{{ item.image.url }}" class="w-full h-56 object-cover rounded-xl">
                </div>
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{item.name}}</h2>
                    <p class="text-gray-400">Price: {{item.price}}</p>
                </div>
            </a>
        </div>
    {% endfor %}
</div>
</div>
{% endblock %}

item/templates/form.html
{% extends 'base.html' %}

{% block title %}{{title}}{%endblock%}

{%block content%}
    <h1 class="mb-6 text-3xl">{{title}}</h1>
    <form method = 'post' action = '.' enctype="multipart/form-data">
        {% csrf_token %}
        <div class="space-y-4 ">
            {{ form.as_p }}
        </div>
        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                {{ form.non_field_errors}}
            </div>
        {% endif %}
        <button class=" mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
{%endblock%}

item/templates/items.html
{% extends 'base.html' %}

{% block title %}Items{%endblock%}

{%block content%}
    <div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
        <div class="col-span-1">
            <form method="get" action="{%url 'item:items'%}">
                <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}" placeholder="Find a bike, a chair or car.">
                <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl ">
                    Search
                </button>
            </form>
            <hr class="mt-6">
            <p class="font-semibold">Categories</p>
            <ul>
                {% for category in categories %}
                    <li class="py-2 px-2 rounded-xl {% if category.id == category_id %} bg-gray-200 {% endif%}">
                        <a href="{% url 'item:items' %}?query={{ query }}&category={{category.id}}">{{category.name}}</a>
                    </li>
                {% endfor %}
            </ul>
            <hr class="mt-6">
            <p class="font-semibold">Clear Filters</p>
            <ul>
                <li><a href="{% url 'item:items' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear</a> </li>
            </ul>
        </div>
        <div class="col-span-3">
            <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
                {% for item in items %}
                    <div class="bg-white shadow-lg rounded-xl overflow-hidden p-4 hover:shadow-2xl hover:scale-105 transition duration-300 ease-in-out">
                        <a href="{% url 'item:detail' item.id %}">
                            <div>
                                <img src="{{ item.image.url }}" class="w-full h-56 object-cover rounded-xl">
                            </div>
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{item.name}}</h2>
                                <p class="text-gray-400">Price: {{item.price}}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{%endblock%}